export const lang = {
  ru: {
    nation: 'Нация',
    type: 'Вид',
    modal: {
      armor: 'Живучесть',
      hp: 'Прочность',
      hull: 'Бронирование корпуса (мм)',
      turret: 'Бронирование башни (мм)',
      weight: 'Масса (кг)',
      ammo: 'Огневая мощь',
      damage: 'Урон',
      penetration: 'Бронепробитие',
      fire_rate: 'Скорострельность (выстр/мин)',
      aim_time: 'Время сведения (с)',
      dispersion: 'Разброс на 100 м (м)',
      max_ammo: 'Боекомплект',
      crew: 'Экипаж',
      range: 'Наблюдение',
      view_range: 'Обзор (м)',
      signal_range: 'Дальность связи (м)',
      speed: 'Передвижение',
      speed_forward: 'Максимальная скорость (км/ч)',
      speed_backward: 'Макс. скорость заднего хода (км/ч)',
      btn_add_compare: 'Добавить для сравнения',
    },
    typeTank: {
      lightTank: 'Легкий танк',
      mediumTank: 'Средний танк',
      heavyTank: 'Тяжёлый танк',
      'AT-SPG': 'ПТ-САУ',
      SPG: 'САУ',
    },
  },
  en: {
    nation: 'Nation',
    type: 'Type',
    modal: {
      armor: 'Vitality',
      hp: 'Strength',
      hull: 'Hull Armor (mm)',
      turret: 'Turret armor (mm)',
      weight: 'Weight (kg)',
      ammo: 'Firepower',
      damage: 'Damage',
      penetration: 'Armor penetration',
      fire_rate: 'Rate of fire (rds / min)',
      aim_time: 'Aiming time (s)',
      dispersion: 'Spread at 100 m (m))',
      max_ammo: 'Ammunition',
      crew: 'Crew',
      range: 'Observation',
      view_range: 'View range (m)',
      signal_range: 'Communication range (m)',
      speed: 'Movement',
      speed_forward: 'Maximum speed (km / h)',
      speed_backward: 'Max. reverse speed (km / h)',
      btn_add_compare: 'Add to Compare',
    },
    typeTank: {
      lightTank: 'Light Tank',
      mediumTank: 'Medium Tank',
      heavyTank: 'Heavy Tank',
      'AT-SPG': 'Tank Destroyer',
      SPG: 'SPG',
    },
  },
  fr: {
    nation: 'Nation',
    type: 'Vue',
    modal: {
      armor: 'Vitalité',
      hp: 'Force',
      hull: 'Blindage de coque (mm)',
      turret: 'Blindage de la tourelle (mm)',
      weight: 'Poids (kg)',
      ammo: 'Puissance de feu',
      damage: 'Endommager',
      penetration: 'Pénétration d`armure',
      fire_rate: 'Cadence de tir (rds / min)',
      aim_time: 'Temps (s) de visée',
      dispersion: 'Écart à 100 m (m)',
      max_ammo: 'Munition',
      crew: 'Équipage',
      range: 'Observation',
      view_range: 'Évaluation (m)',
      signal_range: 'Portée de communication (m)',
      speed: 'Mouvement',
      speed_forward: 'Vitesse maximale (km / h)',
      speed_backward: 'Max. vitesse de marche arrière (km / h)',
      btn_add_compare: 'Ajouter pour comparer',
    },
    typeTank: {
      lightTank: 'Char léger',
      mediumTank: 'Char moyen',
      heavyTank: 'Char lourd',
      'AT-SPG': 'Ch. de chars',
      SPG: 'CAM',
    },
  },
  de: {
    nation: 'Nation',
    type: 'Aussicht',
    modal: {
      armor: 'Vitalität',
      hp: 'Stärke',
      hull: 'Rumpfrüstung (mm)',
      turret: 'Turmpanzerung (mm)',
      weight: 'Gewicht (kg)',
      ammo: 'Feuerkraft',
      damage: 'Beschädigung',
      penetration: 'Rüstungsdurchdringung',
      fire_rate: 'Feuerrate (rds / min)',
      aim_time: 'Zielzeit (en)',
      dispersion: 'Ausbreitung auf 100 m (m)',
      max_ammo: 'Munition',
      crew: 'Besatzung',
      range: 'Überwachung',
      view_range: 'Rückblick (m)',
      signal_range: 'Kommunikationsreichweite (m)',
      speed: 'Bewegung',
      speed_forward: 'Höchstgeschwindigkeit (km / h)',
      speed_backward: 'Max. Rückwärtsgang (km / h)',
      btn_add_compare: 'Hinzufügen zum vergleichen',
    },
    typeTank: {
      lightTank: 'Leichter Panzer',
      mediumTank: 'Mittlerer Panzer',
      heavyTank: 'Schwere Panzer',
      'AT-SPG': 'Jagdpanzer',
      SPG: 'Selbstfahrlafette',
    },
  },
  'zh-cn': {
    nation: '国家',
    type: '看法',
    modal: {
      armor: '活力',
      hp: '力量',
      hull: '船体装甲（mm)',
      turret: '炮塔装甲（mm',
      weight: '重量（公斤',
      ammo: '火力',
      damage: '损害',
      penetration: '护甲穿透',
      fire_rate: '射速（rds / min',
      aim_time: '瞄准时间（秒)',
      dispersion: '传播于100 m（m)',
      max_ammo: '弹药',
      crew: '全体人员',
      range: '观察',
      view_range: '评论（米)',
      signal_range: '通讯范围（米)',
      speed: '移动',
      speed_forward: '最高速度（公里/小时)',
      speed_backward: '最大限度。 倒车速度（公里/小时)',
      btn_add_compare: '加入比较',
    },
    typeTank: {
      lightTank: '轻型坦克',
      mediumTank: '中型坦克',
      heavyTank: '重型坦克',
      'AT-SPG': '坦克歼击车',
      SPG: 'SPG',
    },
  },
};
